name: CloudGame
description: Cloud minigame framework.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: updateme
depend: [WorldGuard]

commands:
    arena:
        description: Allows management of arenas
        permission: cloudgame.admin
        usage: /arena <subcommand> [args]

permissions:
    cloudgame.admin:
        description: Allows managing of cloudgame internals.
