name: MattKOTH
description: King of the hill minigame.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: net.og_mc.mattgame.MattGame

commands:
    arenacreate:
        description: Creates an arena
        permission: mattgame.admin
        usage: /arenacreate <region> [world=current]
    arenaresetspawns:
        description: Resets the spawns of an arena
        permission: mattgame.admin
        usage: /arenaresetspawns <region> [world=current]
    arenasetspawn:
        description: Sets a spawn of an arena
        permission: mattgame.admin
        usage: /arenasetspawn <region> [world=current]
    roomset:
        description: Sets a room
        permission: mattgame.admin
        usage: /roomset <region> [world=current]
    roomunset:
        description: Unsets a room
        permission: mattgame.admin
        usage: /roomunset <region> [world=current]

permissions:
    mattgame.admin:
        description: Allows managing of MattGame.
