name: MattKOTH
description: King of the hill minigame.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: com.simplyian.cloudgame.CloudGame
depend: [WorldGuard]

commands:
    arenacreate:
        description: Creates an arena
        permission: mattkoth.admin
        usage: /arenacreate <region> [world=current]
    arenainfo:
        description: Gets information about the arena
        permission: mattkoth.admin
        usage: /arenainfo
    arenalistspawns:
        description: Lists the spawns of an arena.
        permission: mattkoth.admin
        usage: /arenalistspawns
    arenaresetspawns:
        description: Resets the spawns of an arena
        permission: mattkoth.admin
        usage: /arenaresetspawns
    arenasetname:
        description: Sets the name of an arena
        permission: mattkoth.admin
        usage: /arenasetname
    arenasetspawn:
        description: Sets a spawn of an arena
        permission: mattkoth.admin
        usage: /arenasetspawn

    koth:
        description: KOTH command
        usage: /koth <command>

permissions:
    mattkoth.admin:
        description: Allows managing of MattKOTH.
