name: MattKOTH
description: King of the hill minigame.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: net.og_mc.mattgame.MattGame

commands:
    setroom:
        description: Sets a room
        permission: mattgame.commands.setroom
    unsetroom:
        description: Unsets a room
        permission: mattgame.commands.unsetroom

permissions:
    mattgame.commands.setroom:
        description: Allows setting of a mattgame room
    mattgame.commands.unsetroom:
        description: Allows unsetting of a mattgame room
